Para importar una librería y agregarle un alias, en este caso NumPy:

In [2]:
import numpy as np

Creamos una lista como normalmente lo hacemos:

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Transformamos la lista en un array de la siguiente manera

In [5]:
arr = np.array(lista)

Podemos encontrar el tipo de una variable como sigue:

In [6]:
type(arr)

numpy.ndarray

También podemos imprimir la variable, llamándola. Es un objeto de una dimensión

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos crear una matriz, que tendrá más de una dimensión:

In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Naturalmente, el indexado empieza desde 0. Por ejemplo, para el array arr:

In [10]:
arr[0]

1

y podemos hacer operaciones también:

In [11]:
arr[0] + arr[6]

8

Ahora, algo similar ocurre con las matrices:


In [12]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz[0]

array([1, 2, 3])

Podemos acceder a un elemento en específico de nuestra matriz de la siguiente manera:

In [14]:
matriz[0,2]

3

Como vemos, el primer elemento indica la fila, mientras que el segundo elemento indica la columna.

Ahora, si queremos acceder a varios valores; por ejemplo, a los tres primeros valores del array arr:

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0:3]

array([1, 2, 3])

Podemos notar que toma el elemento de índice cero pero no el elemento de índice tres.

In [17]:
arr[1:6]

array([2, 3, 4, 5, 6])

Si no agregamos el inicio o comienzo del array, por defecto considerará todo desde el inicio. Veamos,

In [18]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

Asimismo, si no agregamos el final, por defecto considerará todos los elementos hasta el final. Veamos,

In [19]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

También podemos considerar toda el array:

In [20]:
arr[::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Y además, podemos tomar los elementos del array por tramos. Es decir, con un paso:

In [21]:
arr[::3]

array([1, 4, 7])

Algo común en Ciencia de Datos es observar el [-1]. Esto indicará el último elemento:

In [22]:
arr[-1]

9

Veamos arr[:-3]. Indicará que queremos todos los elementos desde el elemento de índice -3:

In [25]:
arr[:-3]

array([1, 2, 3, 4, 5, 6])

Todo este proceso es llamado Slicing y también se puede hacer con una matriz:

In [26]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])