In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Si hacemos una condicional directa, vamos a obtener un array con booleanos. Veamos:

In [3]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Guardémoslo en una variable:

In [5]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Veamos lo que sucede si imprimimos el array original, indicando como índice el array que acabamos de guardar:

In [6]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

Esto significa que podemos ingresar condiciones en lugar de los índices del array. Es decir:

In [7]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

Otra manera de hacerlo es como sigue:

In [8]:
arr[arr > 5] = 99

In [9]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

O podemos dar una condición de búsqueda:

In [10]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)