In [1]:
import numpy as np

Generamos un array:

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Creamos una array 'trozo_de_arr' con una porción del array inicial:

In [6]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

Ahora hacemos que todos los elementos de 'trozo_de_arr' sean 0:

In [7]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

Pero, sorpresa! Cuando llamamos al array original 'arr', vemos que los cambios también están reflejados aquí:

In [8]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Esto sucede en NumPy y en muchas de las estructuras que tenemos en Python. Este pequeño error puede dañar por completo un vector, una matriz, un tensor.. Es muy peligroso.

Usemos el comando copy entonces:

In [13]:
arr_copy = arr.copy()

In [14]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Ahora cambiamos todos los elementos de 'arr_copy' por 100:

In [15]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Y cuando llamamos al array original, mantiene su forma y no cambió nada.

In [16]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])