In [1]:
import numpy as np

En python, podemos crear una lista con los número del 0 al 10-1  con la función range:

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Podemos hacer lo mismo con la función arange de NumPy:

In [4]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Además, podemos darle un paso en la tercera entrada de arange:

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Además, podemos crear un array compuesto de ceros en la dimensión que lo pidamos:

In [6]:
np.zeros(3)

array([0., 0., 0.])

Esto es muy útil y muy usado en Ciencia de Datos, veamos por ejemplo:

In [7]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Similarmente, tenemos np.ones:

In [8]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Podemos generar un array de número espaciados entre sí la cantidad que se lo indiquemos con np.linspace:

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

Podemos generar una matriz diagonal unitaria con la dimensión que deseemos con np.eye:

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Es posible crear un número aleatorio con la ayuda de NumPy:

In [13]:
np.random.rand()

0.9698599505863457

Si deseamos un array de cierta dimensión, basta con indicárselo:

In [14]:
np.random.rand(2)

array([0.78584391, 0.08836257])

In [15]:
np.random.rand(2,3)

array([[0.84889452, 0.6081    , 0.17486864],
       [0.23622796, 0.35067298, 0.22923605]])

Si deseamos un número aleatorio que no esté entre 0 y 1, podemos considerar un número aleatorio entero. Veamos:

In [16]:
np.random.randint(1,15)

11

Si deseamos generar número aleatorios en un array, podemos hacerlo también:

In [17]:
np.random.randint(1, 100, (10,10))

array([[43, 38, 16, 12, 24, 81, 80,  5, 45,  8],
       [16, 49, 78,  8, 51, 41, 69, 89,  6, 35],
       [94,  8, 32, 13, 16, 38,  4, 56, 49, 69],
       [39, 97, 54, 69, 93, 15, 50,  1, 49, 49],
       [83, 71, 67, 99, 88, 12, 98, 60, 55, 50],
       [28, 28, 17, 55,  9,  9, 33, 47, 99, 24],
       [47, 98, 44, 98, 68, 50, 93, 91, 94, 82],
       [15, 70, 34, 73, 58, 86,  4, 10, 73, 18],
       [60, 67, 83, 96,  5, 29, 62, 41, 34, 28],
       [ 8,  6,  1, 54, 87, 91, 79, 25, 82, 69]])