In [7]:
import numpy as np

Definamos un array escalar y veamos un dimensión con .ndim:

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

Veamos lo mismo ahora con una vector:

In [3]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1,2,3],[4,5,6,]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[4,5,6]],[[4,5,6],[1,2,3],[9,10,11],[4,5,6]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 4  5  6]]

 [[ 4  5  6]
  [ 1  2  3]
  [ 9 10 11]
  [ 4  5  6]]]


3

Algo muy útil es poder eliminar o agregar dimensiones, esto lo podemos hacer muy fácilmente. Empezemos por hacerlo cuando definimos un nuevo array:

In [11]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

Ahora veamos cómo cambiar la dimensión cuando el array ya está creado:

In [12]:
expand = np.expand_dims(np.array([1,2,3]), axis= 0)
print(expand)
expand.ndim

[[1 2 3]]


2

Con np.squeeze numpy toma los array con dimensión útil y quita las que no se están usando. Veamos:

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
