In [1]:
import numpy as np

Definimos array de una dimensión con 10 número enteros aleatorios:

In [6]:
arr = np.random.randint(1,20,10)
arr

array([15,  1, 10,  2,  5, 17,  1,  9, 13, 18])

Hacemos un reshape para que sea una matriz:

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[16,  1,  4, 18, 16],
       [11, 11, 15, 13,  7]])

Buscamos con la función .max() el máximo valor del array:

In [7]:
arr.max()

18

Buscamos con la función .max() el máximo valor de la matriz:

In [8]:
matriz.max()

18

Podemos restringir la búsqueda dentro de la matriz, si por ejemplo, indicamos que busque solo por filas:

In [10]:
matriz.max(1)

array([18, 15])

O indicar que busque en la matriz por columnas:

In [11]:
matriz.max(0)

array([16, 11, 15, 18, 16])

Ahora, podemos usar .argmax() para encontrar el índice del número máximo. Si hubieran más de 2, solo indicará el primer índice que encuentre:

In [13]:
arr.argmax()

9

In [14]:
matriz.argmax()

3

Si usamos un argumento dentro de argmax podemos indicar que busque por columnas:

In [15]:
matriz.argmax(0)

array([0, 1, 1, 0, 0], dtype=int64)

O que busque por filas:

In [16]:
matriz.argmax(1)

array([3, 2], dtype=int64)

Similarmente a .max(), existe .min() con las mismas funcionalidades:

In [17]:
arr.min()

1

In [18]:
matriz.min(0)

array([11,  1,  4, 13,  7])

In [19]:
matriz.min(1)

array([1, 7])

In [21]:
matriz.argmin(0)

array([1, 0, 0, 1, 1], dtype=int64)

In [22]:
matriz.argmin(1)

array([1, 4], dtype=int64)

In [23]:
arr

array([15,  1, 10,  2,  5, 17,  1,  9, 13, 18])

In [24]:
matriz

array([[16,  1,  4, 18, 16],
       [11, 11, 15, 13,  7]])

Ahora, existe una función llamada .ptp, que resta entre el mayor y menos valor. Pike to pike:

In [25]:
arr.ptp()

17

In [26]:
matriz.ptp()

17

Y en la matriz podemos indicarle que lo haga por ejes. Por columnas por ejemplo:

In [27]:
matriz.ptp(0)

array([ 5, 10, 11,  5,  9])

y por filas:

In [28]:
matriz.ptp(1)

array([17,  8])

Una función útil en estadística o economía es el percentil. En este caso .percentile indicará el valor que se encuentra en el lugar que indiquemos. Como ejemplo en la mitad, pero como no existe, tomará los dos valores medios y hará un promedio:

In [29]:
np.percentile(arr, 50)

9.5

percentil 0 indicará el número más bajo y percentil 100 indicará el mayor número:

In [ ]:
np.percentile(arr, 0)

La función .sort() ordena los número del array de menor a mayor:

In [30]:
arr.sort()
arr

array([ 1,  1,  2,  5,  9, 10, 13, 15, 17, 18])

También en estadística se usa mucho la mediana. En Numpy podemos usar np.median:

In [31]:
np.median(arr)

9.5

Lo mismo podemos usar para encontrar la mediana en una matriz, por ejemplo, por columnas:

In [33]:
np.median(matriz, 0)

array([13.5,  6. ,  9.5, 15.5, 11.5])

O por filas:

In [34]:
np.median(matriz, 1)

array([16., 11.])

Existe también la desviación estándar como .std():

In [35]:
np.std(arr)

6.252199612936234

Asimismo, la varianza que es la desviación estándar al cuadrado:

In [36]:
np.var(arr)

39.089999999999996

Algo importante es también la media como .mean():

In [37]:
np.mean(arr)

9.1

In [38]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [42]:
a.ndim
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
b.ndim

1

In [41]:
b = np.expand_dims(b, axis=0)

In [43]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

surge un error por la dimensión:

In [44]:
np.concatenate((a,b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Lo podemos solucionar cambiando la dimensión o transponiendo la matriz: 

In [46]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])