In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

Si multiplicamos directamente la lista por un entero, la lista se duplicará como tal y no se multiplicarán sus elementos. Veamos:

In [3]:
lista*2

[1, 2, 1, 2]

Creemos un array:

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Para evitar errores y por buenas prácticas, hacemos un copy:

In [8]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Entonces hagamos operaciones aritméticas. NumPy permite acceder a los elementos y no operar con el array como sí sucedía al operar con una lista. Veamos

Multiplicamos un array por un entero:

In [9]:
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Sumamos un array con un entero:

In [10]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Dividimos con el array. Si alguna de las operaciones no está definida arrojará un Warning, pero realizará todas las demás. Veamos:

In [11]:
1/arr2

C:\Users\Aaron\AppData\Local\Temp\ipykernel_9444\1672552411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Elevamos los elementos del array al cuadrado:

In [12]:
arr2**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Podemos sumar elementos de dos arrays distintos:

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Podemos restar elementos de dos arrays distintos:

In [14]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Podemos multiplicar elementos de dos arrays distintos:

In [15]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Veamos las operaciones con matrices:

In [19]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Veamos las operaciones con matrices:

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [22]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

La transpuesta de la matriz2

In [23]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Ahora bien, qué sucede si queremos hacer un producto matricial:

In [24]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

Otra forma alternativa de hacer el mismo producto matricial es con @:

In [25]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])