In [1]:
import numpy as np

Generemos un array de 3 filas y 2 columnas con elementos aleatorios:

In [6]:
arr = np.random.randint(1,10,(3,2))
arr

array([[5, 3],
       [9, 2],
       [2, 3]])

Con la función shape podemos saber la dimensión del array:

In [5]:
arr.shape

(3, 2)

Con reshape podemos reasignar la dimensión y el ordenamiento de nuestro array:

In [7]:
arr.reshape(1,6)

array([[5, 3, 9, 2, 2, 3]])

In [9]:
arr.reshape(2,3)

array([[5, 3, 9],
       [2, 2, 3]])

Adicionalmente, podemos hacer un reshape de la siguiente manera:

In [10]:
np.reshape(arr, (1,6))

array([[5, 3, 9, 2, 2, 3]])

In [11]:
arr

array([[5, 3],
       [9, 2],
       [2, 3]])

El lenguaje 'C' hace un reshape por filas. Es decir, toma la primera fila y la empieza a ordenar como se indicó en el reshape, luego toma la segunda y así hasta terminar.

In [12]:
np.reshape(arr, (2,3), 'C')

array([[5, 3, 9],
       [2, 2, 3]])

Por otro lado, el lenguaje 'Fortran' lo hace de manera diferente. Toma la primera columna y la ordena como se indicó en el reshape, luego la segunda columna y así hasta terminar.

In [13]:
np.reshape(arr, (2,3), 'F')

array([[5, 2, 2],
       [9, 3, 3]])

Se puede hacer de otra manera, es decir, a como mejor esté en nuestro sistema y así que la máquina escoja cuál es el mejor ordenamiento:

In [14]:
np.reshape(arr, (2,3), 'A')

array([[5, 3, 9],
       [2, 2, 3]])

Python lo ordena como lo hace 'C' y esto es porque Python está hecho en C.

Veamos un último ejemplo:

In [16]:
array = np.random.randint(1, 100, (5,5))
array

array([[19, 65, 75, 96, 65],
       [76, 13, 61, 38, 92],
       [34, 81, 86, 50, 28],
       [ 6, 74, 45, 91, 52],
       [92, 31, 13, 52,  7]])

Reordenaremos y veamos:

In [17]:
array.reshape(1,25)

array([[19, 65, 75, 96, 65, 76, 13, 61, 38, 92, 34, 81, 86, 50, 28,  6,
        74, 45, 91, 52, 92, 31, 13, 52,  7]])

Si intentamos darle un reordenamiento que no respete la cantidad de elementos, surgirá un error:

In [18]:
array.reshape(1,10)

ValueError: cannot reshape array of size 25 into shape (1,10)