In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

Para evidenciar qué tipo de datos está manejando un array, usamos .dtype:

In [5]:
arr.dtype

dtype('int32')

Nosotros podemos cambiar el dtype:

In [7]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [8]:
arr

array([1., 2., 3., 4.])

Si en algún momento nos encontramos con un datos definido con un tipo de dato que no nos gusta, lo podemos cambiar con ayuda de numpy con .astype:

In [9]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [10]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

Asimismo, podemos también cambiar a un tipo booleano con .astype:

In [13]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

De la misma manera, podemos llevarlo a un tipo texto:

In [14]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

Y en viceversa, podemos pasar de tipo texto a tipo entero:

In [15]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

En el caso anterior debemos tener cuidado en no tener una texto que no pueda pasarse a entero, veamos un ejemplo:

In [16]:
arr = np.array(['Hola','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'Hola'

En resumen, para cambiar el tipo de dato de los elementos de un array es importante que todos los elementos sean de un mismo tipo, de otro modo la capacidad de Numpy para su optimización se vería afectado y quizá surjan errores como los que se ven en la celda anterior.